In [132]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [133]:
%autoreload 2
import numpy as np
import seaborn as sns
import pandas as pd
import sklearn as sk
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

In [134]:
terms = ['red','blue','dragon','pheonix']
documents = {
    'd1':[1,1,1,1],
    'd2':[0,0,1,0],
    'd3':[0,0,1,1],
    'd4':[1,2,1,2],
    'd5':[1,1,0,0],
    'd6':[1,1,1,1],
    'd7':[0,3,0,0],
    'd8':[1,0,0,1],
    'd9':[1,0,0,1],
    'd10':[2,1,1,0],
}

In [135]:
tf = [7,9,6,8]
df = [6,6,7,6]
idf = np.log10(10/np.array(df))
tf_idf = {}

In [136]:
idf

array([0.22184875, 0.22184875, 0.15490196, 0.22184875])

In [137]:
for dkey, document in documents.items():
    d = []
    for index,value in enumerate(idf):
        d.append(document[index]*value)
    tf_idf[dkey] = d

In [138]:
df = pd.DataFrame(tf_idf.values(), columns=terms)

In [139]:
df

red      blue    dragon   pheonix
0  0.221849  0.221849  0.154902  0.221849
1  0.000000  0.000000  0.154902  0.000000
2  0.000000  0.000000  0.154902  0.221849
3  0.221849  0.443697  0.154902  0.443697
4  0.221849  0.221849  0.000000  0.000000
5  0.221849  0.221849  0.154902  0.221849
6  0.000000  0.665546  0.000000  0.000000
7  0.221849  0.000000  0.000000  0.221849
8  0.221849  0.000000  0.000000  0.221849
9  0.443697  0.221849  0.154902  0.000000

In [140]:
query = [0,0,0,idf[3]]

In [141]:
similarities = []

In [142]:
similarities.append(cosine_similarity(list(tf_idf.values()), [query]))

In [143]:
similarities.append(euclidean_distances(list(tf_idf.values()), [query]))

In [144]:
normalized_tf_idf = {}

for dkey, vector in tf_idf.items():
    magnitude = np.sqrt(np.sum(np.array(vector)**2))
    normalized_vector = np.array(vector) / magnitude
    normalized_tf_idf[dkey] = normalized_vector

In [145]:
sim = []
for dkey, vector in normalized_tf_idf.items():
    sim.append([np.sqrt(np.sum((vector - query)**2))])
similarities.append(np.array(sim))

In [146]:
similarities

[array([[0.53547738],
        [0.        ],
        [0.81991225],
        [0.64931204],
        [0.        ],
        [0.53547738],
        [0.        ],
        [0.70710678],
        [0.70710678],
        [0.        ]]),
 array([[0.34989763],
        [0.27057621],
        [0.15490196],
        [0.56506267],
        [0.38425331],
        [0.34989763],
        [0.70154734],
        [0.22184875],
        [0.22184875],
        [0.56506267]]),
 array([[0.90090338],
        [1.02431288],
        [0.82790329],
        [0.87242119],
        [1.02431288],
        [0.90090338],
        [1.02431288],
        [0.8575986 ],
        [0.8575986 ],
        [1.02431288]])]